// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FsArticleCard: typeof import('./src/components/FsArticleCard/FsArticleCard.vue')['default']
    FsAvatarCard: typeof import('./src/components/FsAvatarCard/FsAvatarCard.vue')['default']
    FsBackTop: typeof import('./src/components/FsBackTop/FsBackTop.vue')['default']
    FSBannerCarousel: typeof import('./src/components/FsBannerCarousel/FSBannerCarousel.vue')['default']
    FsBlogCard: typeof import('./src/components/FsBlogCard/FsBlogCard.vue')['default']
    FsCommentCard: typeof import('./src/components/FsCommentCard/FsCommentCard.vue')['default']
    FsDrawer: typeof import('./src/components/FsDrawer/FsDrawer.vue')['default']
    FsImage: typeof import('./src/components/FsImage/FsImage.vue')['default']
    FsInitLoading: typeof import('./src/components/FsInitLoading/FsInitLoading.vue')['default']
    FsLinkCard: typeof import('./src/components/FsLinkCard/FsLinkCard.vue')['default']
    FsMessageCard: typeof import('./src/components/FsMessageCard/FsMessageCard.vue')['default']
    FsMoveCover: typeof import('./src/components/FsMoveCover/FsMoveCover.vue')['default']
    FsNavBar: typeof import('./src/components/FsNavBar/FsNavBar.vue')['default']
    FsRecommendCard: typeof import('./src/components/FsRecommendCard/FsRecommendCard.vue')['default']
    FsSearchCard: typeof import('./src/components/FsSearchCard/FsSearchCard.vue')['default']
    FsSideCard: typeof import('./src/components/FsSideCard/FsSideCard.vue')['default']
    FsTimer: typeof import('./src/components/FsTimer/FsTimer.vue')['default']
    FsVirtualList: typeof import('./src/components/FsVirtualList/FsVirtualList.vue')['default']
    FsWaterFall: typeof import('./src/components/FsWaterFall/FsWaterFall.vue')['default']
    FsWebCard: typeof import('./src/components/FsWebCard/FsWebCard.vue')['default']
    FsWebFooter: typeof import('./src/components/FsWebFooter/FsWebFooter.vue')['default']
    FsWebTab: typeof import('./src/components/FsWebTab/FsWebTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
